# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b80f8298c0c439961733b0c25242527ee14e9328a19a4b1c953b8bc3ed21ae6beb9522b0941d2ea98e8de87946da55bd085c99e1893de7daa3de8ab0278b87bf

test:
  secret_key_base: 03747119480abc5aefdbb280714e4a67a296e1d5a8ed417867d39d7ca82619263a8ed7845be9abb673d7b576c26d5fb3794cb867158dbc748b8a7357802f2417

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: d618b1e5bd5f993560a830725474049f4ff06b8fbd7dd2fc6e74529ab701d47230a4637824c8ee4700bc4ee8b229f60e342b17dafef5767a6d0b1b6368ef8653
